name: Determine Editted TF Slices

inputs:
  shell:
    description: "private -- do not use"
    default: env ./tacos-gha/lib/ci/default-shell {0}

outputs:
  slices:
    description: "JSON list of paths to relevant TF/TG slices"
    value: ${{ steps.list-slices.outputs.slices }}

runs:
  using: composite

  steps:
    - uses: ./tacos-gha/.github/actions/just-the-basics

    - id: files
      uses: dorny/paths-filter@v3.0.1
      with:
        filters: "all: ['**']"
        list-files: json

    - name: List Slices
      id: list-slices
      shell: ${{inputs.shell}}
      run: |
        gha-log-as-step-summary \
          "$TACOS_GHA_HOME/"lib/ci/list-slices <<'EOF'
        ${{steps.files.outputs.all_files}}
        EOF
