#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

set -x

# disable the cache plugin to ensure we get data from all tests
# otherwise, by default, we only run the "last failed" tests
if ! coverage-enabled ./lib/make/test \
  -p no:cacheprovider \
  --override-ini="addopts=--durations-min=10 -s -vv --doctest-modules" \
  "$@" \
; then
  : 'some tests failed :('
fi
