#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

# relative HERE, for prettier logs
HERE="$(dirname "$0")"

set -x

git-ls-python | xargs -r black
git-ls-python | xargs -r isort
git ls-files | "$HERE/"bin/prettier
