#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

set -x

git ls-files '**/*.py' |
  xargs -r black \
;

git ls-files '**/*.py' |
  xargs -r isort \
;

git ls-files |
  # prettier doesn't like symlinks ¯\_(ツ)_/¯
  file --mime-type --no-pad --files-from=- |
  grep -v 'inode/symlink$' |
  sed 's@: .*@@' |
  xargs -r prettier --write --ignore-unknown \
;
