#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

set -x

git ls-files '**/*.py' |
  xargs -r black

git ls-files '**/*.py' |
  xargs -r isort

git ls-files |
  xargs -r prettier --write --ignore-unknown
