#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

set -x

fail=()
if ! pyright .; then
  fail+=(pyright)
fi
if ! mypy .; then
  fail+=(mypy)
fi
if ! git ls-files '*/py.typed' |
    xargs dirname |
    xargs -n1 -tr \
      env PYTHONPATH="$PWD" \
        pyright \
        --ignoreexternal \
        --verifytypes \
      \
    ;
then
  fail+=(pyright-verifytypes)
fi

if ! git ls-files |
  file --mime-type --no-pad --files-from=- |
    grep ': text/x-shellscript$' |
    sed 's@: text/x-shellscript$@@' |
    xargs -r shellcheck \
  ;
then
  fail+=(shellcheck)
fi


set +x
if [[ "${fail[*]:-}" ]]; then
  echo "FAIL (${fail[*]})"
  exit 1
else
  echo PASS
fi
