#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

# relative HERE, for prettier logs
HERE="$(dirname "$0")"

set -x

fail=()
if ! git-ls-python | xargs -r "$HERE/"bin/pyright; then
  fail+=(pyright)
fi
if ! "$HERE/"bin/mypy; then
  fail+=(mypy)
fi

# get directories that contain a py.typed file:
if ! git ls-files '*/py.typed' |
    xargs dirname |
    xargs -n1 -tr "$HERE/"bin/pyright-verifytypes
then
  fail+=(pyright-verifytypes)
fi

if ! "$HERE/"bin/shellcheck; then
  fail+=(shellcheck)
fi


set +x
if [[ "${fail[*]:-}" ]]; then
  echo "FAIL (${fail[*]})"
  exit 1
else
  echo PASS
fi
