#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging
HERE="$(cd "$(dirname "$0")"; pwd)"

set -x

fail=()
if ! git-ls-python | xargs -r pyright; then
  fail+=(pyright)
fi
if ! git-ls-python | xargs -r mypy; then
  fail+=(mypy)
fi

python -c 'import _pytest; print(_pytest); import _pytest.doctest; print(_pytest.doctest); print(_pytest.doctest.DoctestItem)'

# get directories that contain a py.typed file:
if ! git ls-files '*/py.typed' |
    xargs dirname |
    xargs -n1 -tr "$HERE/"bin/pyright-verifytypes
then
  fail+=(pyright-verifytypes)
fi

if ! git-ls-sh | xargs -r shellcheck; then
  fail+=(shellcheck)
fi


set +x
if [[ "${fail[*]:-}" ]]; then
  echo "FAIL (${fail[*]})"
  exit 1
else
  echo PASS
fi
