#!/bin/bash
set -euxo pipefail
venv="./$1"

onerror() {
  rm -rf "$venv"
}

trap onerror ERR
onerror  # let's start clean

brew bundle
pyenv install -v --skip-existing
pyenv exec python -m venv "$venv"
"$venv"/bin/pip install -r requirements-dev.txt
touch "$venv"
