#!/bin/bash
set -euo pipefail
exec >&2  # all output is logging

VIRTUAL_ENV=${VIRTUAL_ENV:-$PWD/venv}
cleanup() { rm -rf "$VIRTUAL_ENV"; }
trap cleanup ERR

set -x

: lets start clean
cleanup
pyenv install -v --skip-existing
pyenv exec python3.12 -Pm venv "$VIRTUAL_ENV"
: should be the venv pip:
which pip
pip install -r requirements-dev.txt "$@"

touch "$VIRTUAL_ENV"
