name: Just the Basics
description: used in "determine slices" and "per slice" matrix jobs

inputs:
  shell:
    description: "private -- do not use"
    default: env ./tacos-gha/lib/ci/default-shell {0}

runs:
  using: composite

  steps:
    - name: show original environ
      shell: bash -euxo pipefail {0}
      run: |
        export TACOS_GHA_HOME="$PWD/tacos-gha"
        ./tacos-gha/bin/gha-printenv original

    # default-shell requires direnv
    - name: install direnv
      uses: HatsuneMiku3939/direnv-action@v1
      with:
        # action_path contains the directory of this action (just-the-basics)
        # traverse up 3 times to reach the envrc in the root of the repo.
        path: ${{ github.action_path }}/../../../.envrc
    - name: show GHA contexts
      shell: ${{inputs.shell}}
      run: |
        : GHA contexts: <<'EOF'
          github:   # too huge, enable debug logging to see
          env:      ${{ toJSON(env) }},
          vars:     # not valid in custom action
          job:      ${{ toJSON(job) }},
          jobs:     # for reusable workflows only
          steps:    ${{ toJSON(steps) }},
          runner:   ${{ toJSON(runner) }},
          secrets:  # not valid in custom action
          strategy: ${{ toJSON(strategy) }},
          matrix:   ${{ toJSON(matrix) }},
          needs:    # not valid in custom action
          inputs:   ${{ toJSON(inputs) }},
        EOF
        : DOC: https://docs.github.com/en/actions/learn-github-actions/contexts
    - name: "debug: show `github` context"
      if: ${{runner.debug}}
      shell: ${{inputs.shell}}
      run: |
        : its huge... expand script, above to view <<'EOF'
          github:   ${{ toJSON(github) }},
        EOF
    - name: enable `gh` cli
      shell: ${{inputs.shell}}
      run: |
        gha-set-env 'GH_TOKEN' <<< "$GH_TOKEN"
      env:
        GH_TOKEN: ${{ github.token }}
    - name: get python version
      shell: ${{inputs.shell}}
      run: |
        grep -Ev '^#' "$TACOS_GHA_HOME/".python-version |
          gha-set-env 'PYTHON_VERSION' \
        ;
    - name: install python ${{env.PYTHON_VERSION}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}
