name: Terraform Apply

on:
  workflow_dispatch: null
  pull_request:
    types:
      - labeled

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_apply.yml@stable
    with:
      tacos_gha_ref: refs/heads/stable
# Add keys here if your terraform/terragrunt gets modules from a private repo
# separate from the repo that TACOS is installed in.
#    secrets:
#      ssh-private-key: |
#        ${{ secrets.YOUR_PRIVATE_KEY }}
#        ${{ secrets.YOUR_OTHER_PRIVATE_KEY }}
