name: Terraform Conflict

on:
  workflow_dispatch: null
  pull_request_target:
    types:
      - closed
      - converted_to_draft
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  tacos-gha:
    uses: getsentry/tacos-gha/.github/workflows/tacos_conflict.yml@stable
    with:
      tacos_gha_ref: refs/heads/stable
