name: 'Matrix Fanin'
description: 'Collect all JSON files from the matrix and combine them into a single file (matrix-fanin.json).'
inputs:
  json-file-prefix:
    description: 'The prefix of the JSON files to combine.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download artifacts
      uses: 'actions/download-artifact@v4'
      with:
        merge-multiple: true
        pattern: ${{ inputs.json-file-prefix }}*

    - name: Combine JSON files
      shell: bash
      run: |
        jq -s add $(find . -name "*.json") > matrix-fanin.json
