name: 'Prepare Summary'
description: 'Downloads all artifacts from the current workflow run and prepares a summary of the results.'
inputs:
  artifact-path:
    description: 'The path to the artifact to download.'
    required: true
  process-file-command:
    description: 'A command or script used to process each file.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Download artifacts'
      uses: 'actions/download-artifact@v4'
      with: 
        merge-multiple: true
        pattern: ${{ inputs.artifact-path }}/*
        path: ${{ inputs.artifact-path }}
    
    - name: 'Prepare summary'
      shell: bash
      run: |
        ls -laR ${{ inputs.artifact-path }} || true

        printf "SUMMARY=" >> "$GITHUB_ENV"
        jq -cs add ${{ inputs.artifact-path }}/*.json |
          tee -a "$GITHUB_ENV" |
          jq . \
        ;

