#!/bin/bash
# Wrap terragrunt a little to set some CI-friendly defaults.
# We use the `terragrunt` name so that CI shows copy-pasteable commands.
# *All* settings here should represent behaviors that people "should expect" to
# change between CI and local commands.
set -euo pipefail

REPO_ROOT=${REPO_ROOT:-'$^'}  # default: a regex that can't match
TF_PLUGIN_CACHE_DIR=${TF_PLUGIN_CACHE_DIR:-'$^'}
TERRAGRUNT_DOWNLOAD=${TERRAGRUNT_DOWNLOAD:-'$^'}

sed_norm_log() {
  # remove distracting output from terragrunt logs
  sed "
  # shorten $PWD to .
  s#$PWD\>#.#

  # make long paths more symbolic
  s#~/#$HOME#g
  s#$TERRAGRUNT_DOWNLOAD\>#\$TERRAGRUNT_DOWNLOAD#g
  s#$TF_PLUGIN_CACHE_DIR\>#\$TF_PLUGIN_CACHE_DIR#g
  s#$REPO_ROOT\>#\$REPO_ROOT#g
  s#$HOME\>#\$HOME#g

  # remove ./ from 'terragrunt module prefix'
  s#^\[\./#[#
  # remove unecessary '.' terragrunt module prefix
  s#^\[\.\] ##
"
}

## Terragrunt
#if ! tty-exists; then
export TERRAGRUNT_NON_INTERACTIVE=true
# configured in tacos-gha.demo/terraform/terragrunt-base.hcl
# TODO: auto-configure terragrunt retry patterns in tacos-gha
export TERRAGRUNT_NO_AUTO_RETRY=false
#fi
### # this is necessary for recursive init
### export TERRAGRUNT_NO_AUTO_INIT=false
# these should *all* be IAC'd
export TERRAGRUNT_FAIL_ON_STATE_BUCKET_CREATION=true
# shown by default, but overrideable
export TERRAGRUNT_INCLUDE_MODULE_PREFIX=${TERRAGRUNT_INCLUDE_MODULE_PREFIX:-true}
# we'll be implicit
export TERRAGRUNT_NO_AUTO_APPROVE=false

# Don't try this at home, kids!
# * we use tf-lock-acquire to take the lock, before terragrunt starts
# * we run `terraform refresh` separately, in ci-tf-init
export TF_CLI_ARGS=""
export TF_CLI_ARGS_init="-lock=false"
export TF_CLI_ARGS_refresh="-lock=false -refresh=false"
export TF_CLI_ARGS_plan="-lock=false -refresh=false"
export TF_CLI_ARGS_apply="-lock=false -refresh=false"

export DEBUG="${DEBUG:-}"
if (( DEBUG >= 1 )); then
  export TERRAGRUNT_LOG_LEVEL=debug
  set -x
else
  # NOTE: log level "error" doesn't show the terraform error =.=
  export TERRAGRUNT_LOG_LEVEL=info
fi
if (( DEBUG >= 3 )); then
  # very noisy!
  export TF_LOG=debug
fi

TERRAGRUNT="$(which terragrunt)"
while [[ "$TERRAGRUNT" -ef "$0" ]]; do
  TERRAGRUNT="$(super "$TERRAGRUNT")"
done

# sed: shorten the absurdly long "module prefix", but don't combine stdout/err
script -q /dev/null "$TERRAGRUNT" "$@" \
  1> >( sed_norm_log >&1 ) \
  2> >( sed_norm_log >&2 ) \
;
