name: "Matrix Fan-in"
description:
  "Collect all JSON files from the matrix and combine them into a single file
  (matrix-fan-in.json)."

inputs:
  path:
    description: Must match matrix-fan-out `path`.
    default: ./matrix-fan-out
  pattern:
    description: |-
      Optionally filter which matrix results to include e.g. "color=blue"
      syntax: @actions/glob
    default: "*"
  shell:
    description: "private -- do not use"
    default: bash -euxo pipefail {0}

runs:
  using: composite

  steps:
    - shell: ${{ inputs.shell }}
      id: vars
      env:
        MATRIX_FAN_OUT_PATH: ${{ inputs.path }}
      run: |
        (
          "$GITHUB_ACTION_PATH/"set-artifact-name.sh "$MATRIX_FAN_OUT_PATH"
          echo matrix_tmp=matrix-fan-in.tmp
        ) | tee -a "$GITHUB_OUTPUT"

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ steps.vars.outputs.artifact }}*${{ inputs.pattern }}*
        path: ${{ steps.vars.outputs.matrix_tmp }}

    - name: fix up archive files
      shell: bash
      env:
        MATRIX_TMP: ${{ steps.vars.outputs.matrix_tmp }}
        MATRIX_FAN_OUT_PATH: ${{ inputs.path }}

      # note: "$GITHUB_ACTION_PATH" contains this action directory's path
      run: |
        "$GITHUB_ACTION_PATH/"rename-tmp-dirs.sh

### # DEBUG:
### - name: Start SSH
###   if: always()
###   uses: lhotari/action-upterm@v1
###   with:
###     # the job "actor", plus a few others are allowed ssh access
###     limit-access-to-actor: true
###     limit-access-to-users: bukzor,kneeyo1
