name: "Matrix Fan-in"
description:
  "Collect all JSON files from the matrix and combine them into a single file
  (matrix-fan-in.json)."

inputs:
  path:
    description: Must match matrix-fan-out `path`.
    default: ./matrix-fan-out
  fan-out-files:
    description: |-
      Optionally filter which fan-out files to include in the fan-in.
      syntax: find(1) -name
    default: matrix*.json
  pattern:
    description: |-
      Optionally filter which matrix results to include e.g. "color=blue"
      syntax: @actions/glob
    default: "*"
  shell:
    default: bash -euxo pipefail {0}

runs:
  using: composite

  steps:
    - shell: ${{ inputs.shell }}
      env:
        MATRIX_FAN_OUT_PATH: ${{ inputs.path }}
      run: |
        "$GITHUB_ACTION_PATH/"artifact-name.sh "$MATRIX_FAN_OUT_PATH" |
          tee -a "$GITHUB_ENV"

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ env.artifact_name }} *${{ inputs.pattern }}*
        path: matrix-fan-in.tmp

    - name: Combine JSON files
      shell: bash
      env:
        MATRIX_FAN_OUT_PATH: ${{ inputs.path }}
        MATRIX_FAN_OUT_FILES: ${{ inputs.fan-out-files }}

      # note: "$GITHUB_ACTION_PATH" contains this action directory's path
      run: |
        "$GITHUB_ACTION_PATH/"combine-json.sh "$MATRIX_FAN_OUT_PATH" "$MATRIX_FAN_OUT_FILES"
