#!/bin/bash
set -euo pipefail
# Run a command, and shorten its output if it succeeds.

tmp="$(mktemp)"
trap 'rm "$tmp"' EXIT
exec >&2  # only logging output here

export DEBUG="${DEBUG:-}"
if (( DEBUG >= 1 )); then
  "$@"
elif ( set -x; "$@" >"$tmp" 2>&1 ); then
  length=$(wc -l <"$tmp")
  if (( length <= 30 )); then
    cat "$tmp"
  else
    head "$tmp"
    echo "... $((length - 20)) lines snipped -- command succeeded"
    tail "$tmp"
  fi
else
  status="$?"
  echo "ERROR: command failed: $*"
  cat "$tmp"
  exit "$status"
fi
