#!/bin/bash
set -euo pipefail

tmp="$(mktemp)"
trap 'rm "$tmp"' EXIT
exec >&2  # only logging output here

if ( set -x; "$@" >"$tmp" 2>&1 ); then
  length=$(wc -l <"$tmp")
  if (( length <= 30 )); then
    cat "$tmp"
  else
    head "$tmp"
    echo "... $((length - 20)) lines elided -- command succeeded"
    tail "$tmp"
  fi
else
  status="$?"
  echo "ERROR: command failed: $*"
  cat "$tmp"
  exit "$status"
fi
