#!/bin/bash
set -euo pipefail
# attach subcommand to an interactive terminal, if possible

export DEBUG="${DEBUG:-}"
if (( DEBUG >= 4 )); then
  set -x
fi

# NOTE: a simple readabilty check (i.e. [ -r) gives false positives
if ( : < /dev/tty ) 2>/dev/null; then
  if [[ /dev/fd/1 -ef /dev/fd/2 ]]; then
    : tty-attach: keep stdout/stderr combined
    exec 0</dev/tty 2>/dev/tty 1>&2
  else
    : tty-attach: keep stdout separate
    exec 0</dev/tty 2>/dev/tty
  fi
  flock /dev/tty "$@"
else
  "$@"
fi
