#!/usr/bin/env -S python3 -sS
"""Undo `ghaencode`. For details, see `ghaencode`."""
from __future__ import annotations

import html


def main():
    from sys import stdin
    from sys import stdout

    for line in stdin.buffer:
        stdout.buffer.write(
            html.unescape(line.decode("latin1")).encode("latin1")
        )


if __name__ == "__main__":
    raise SystemExit(main())
