#!/usr/bin/env -S python3 -sS
r"""
usage: ghaencode <<< xyz
"""

from __future__ import annotations

import ghaencode

USAGE = (__doc__ + ghaencode.DOC).strip()


def main():
    from sys import stdin
    from sys import stdout

    if stdin.isatty():
        return USAGE

    for line in stdin:
        if line.endswith("\n"):
            eol = "\n"
            line = line[:-1]
        else:
            eol = ""

        stdout.write(ghaencode.ghaencode(line))
        stdout.write(eol)


if __name__ == "__main__":
    raise SystemExit(main())
