#!/bin/bash
# Some presets for use in all GHA shell steps.
# This is the "inner" half, which runs after we switch user via `sudo`
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"

if [[ "${DEBUG}" ]]; then
  gha-printenv post-sudo
fi

# prefix debug lines with a fancy-looking "prompt", randomly colored
export PS4
PS4=$'+ \e['"$("$HERE/"prompt-color)"'m$\e[m '

# encourage programs to use full color -- github logs handle it nicely
export TERM=xterm-256color
export CLICOLOR=truecolor
export COLORTERM=truecolor

if [[ "${TF_ROOT_MODULE:-}" ]]; then
  (set -x; cd "$TF_ROOT_MODULE")  # just so it shows in logs
  cd "$TF_ROOT_MODULE"
fi

: bring in the users environment
eval="$(direnv allow; direnv export bash)"
eval "$eval"
unset DIRENV_DIFF  # give direnv amnesia

: bring in the tacos-gha environment vars
eval="$(cd "$HERE"; direnv allow; direnv export bash)"
eval "$eval"
unset DIRENV_DIFF  # give direnv amnesia

gha-printenv

# the default shell (under github actions) is:
# bash --noprofile --norc -eo pipefail {0}
# added: stop on undefined variables, show all commands
exec bash --noprofile --norc -eo pipefail -ux "$@"
