#!/bin/bash
# Some presets for use in all GHA shell steps.
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"

# minimal bootstrapping: no envrc is loaded till post-sudo
export TACOS_GHA_HOME PATH DEBUG
TACOS_GHA_HOME="${TACOS_GHA_HOME:-"$(cd "$HERE"/../..; pwd)"}"
PATH="$TACOS_GHA_HOME/bin:$TACOS_GHA_HOME/lib/ci/bin:$PATH"
DEBUG="${DEBUG:-"${RUNNER_DEBUG:-}"}"

: combine stdout to stderr, to prevent out-of-order interleaving
exec >&2

: make sure github command-files are writable
chmod -R g+rw "$(dirname "$GITHUB_OUTPUT")"

sudo=(
  # switch user to "$USER" (by default this is a noop)
  sudo --preserve-env -u "$USER"

  # sudo refuses to preserve certain vars: https://github.com/sudo-project/sudo/blob/main/plugins/sudoers/env.c#L138
  env PATH="$PATH"

  # the "inner half" of this script
  default-shell-post-sudo

  # pass along our arguments
 "$@"
)

exec "${sudo[@]}"
