#!/bin/bash
set -euo pipefail

pr_url="$1"

gha-set-env 'GITHUB_PR_URL' <<< "$pr_url"

# get all reviews
gh pr view "$pr_url" --json reviews |
  # keep only the approving reviews
  jq '.reviews | map(select(.state == "APPROVED"))' |
  # prettify
  jq 'map(.author.login) | join(", ")' -r |
  # value is prettified listing of approvers or empty-string
  gha-set-env 'GITHUB_PR_APPROVERS' \
;

# NOTE: it's possible to have approvers but not be approved, due to codeowners
# NOTE: empty string for reviewDecision signifies no review is required
gh pr view "$pr_url" --json reviewDecision |
  jq '.reviewDecision == "APPROVED" || .reviewDecision == "" ' |
  gha-set-env 'GITHUB_PR_APPROVED' \
;

gh pr view "$pr_url" --json state --jq .state |
  gha-set-env 'GITHUB_PR_STATE' \
;
