#!/bin/bash
# stdin: json listing of all files editted
set -euo pipefail

"$TACOS_GHA_HOME/"lib/terragrunt/slices |
  python3 -m lib.tacos.terraformers
  jq -R |
  jq -cs |
  gha-set-output terraformers |
  # prettify
  jq . \
;
