#!/bin/bash
# stdin: json listing of all files editted
set -euo pipefail

jq '.[]' --raw-output |
  python3 -m lib.tacos.dependent_slices "$1" |
  # transform newline-delimited list into json:
  jq -R |
  jq -cs |
  gha-set-env TF_ROOT_MODULES |
  gha-set-output slices |
  # prettify
  jq . \
;
