#!/bin/bash
set -euo pipefail

set -x
cd "$TF_ROOT_MODULE"
if tf-lock-acquire "$@" | gha-set-env TF_LOCK_ID; then
  gha-set-env TF_LOCK <<< true
else
  status="$?"
  gha-set-env TF_LOCK <<< false
  exit "$status"
fi
