#!/bin/bash
set -euo pipefail

set -x
cd "$TF_ROOT_MODULE"
if gha-set-env TF_LOCK_ID tf-lock-acquire "$@"; then
  gha-set-env TF_LOCK echo true
else
  status="$?"
  gha-set-env TF_LOCK echo false
  exit "$status"
fi
