#!/bin/bash

summary=""

for file in lock_result_*/lock_result.txt; do
  if [[ -f "$file" ]]; then
    result=$(bash -c './lib/ci/process-lock-result "$0"' "$file")
    summary+="$result,"
  else
    echo "No lock result file found: $file"
  fi
done

echo "lock_summary=$summary" >> "$GITHUB_OUTPUT"
