#!/bin/bash
set -euxo pipefail
export TERRAGRUNT_INCLUDE_MODULE_PREFIX=false
if "$GITHUB_PR_DRAFT"
then
    lock="false"
    cmd=()
else
    lock="true"
    cmd=(tf-lock "$TF_ROOT_MODULE" -- )
fi

cmd+=(env --chdir="$TF_ROOT_MODULE"
      terragrunt-noninteractive run-all
      plan -out tfplan -lock="$lock")

log=plan-log.hcl

"${cmd[@]}" 2>&1 | tee "$log" && status=$? || status=$?

summary="$(
  if ! tac "$log" | grep -Ei -m1 'Plan:|No changes'; then
    echo "summary failed!($?)"
  fi
)"

gha-step-summary <<EOF
### TACOS Plan: $TF_ROOT_MODULE

<details>
  <summary>$summary</summary>

\`\`\`console
$ $(sh-quote "${cmd[@]}")
\`\`\`

\`\`\`hcl
$(cat plan-log.hcl)
\`\`\`

</details>
EOF

artifact_path="$TF_ROOT_MODULE/tfplan"
gha-set-output artifact_path cat <<< "$artifact_path"
# Invalid characters include: " : < > | * ? \r \n \ /
gha-set-output artifact_name tr / ' ' <<< "$artifact_path"

exit "$status"
