#!/bin/bash
set -euo pipefail
export TERRAGRUNT_INCLUDE_MODULE_PREFIX=false

refuse() {
    reason="$1"
   (
   echo "### TACOS Apply: $TF_ROOT_MODULE"
   cat  # pass deeper explanation via stdin
   echo
   echo "Apply request refused: $reason"
EOF
) | gha-step-summary >/dev/null
    exit 1
}

# NOTE: approval is different than approvers, due to codeowners
if ! "$GITHUB_PR_APPROVED"; then
    refuse "PR has no approvals" <<EOF
Production changes must be peer-reviewed.
Please try again after code review.
EOF
fi

if "$GITHUB_PR_DRAFT"; then
    refuse "PR is not Ready" <<EOF
Draft PRs cannot be applied.
Please try again after code review.
EOF
fi

if [[ "$GITHUB_PR_STATE" != "OPEN" ]]; then
    refuse "PR is not open" <<EOF
Applies are only allowed for open PRs.
You may try reopening the PR first.
EOF
fi

cmd=(
  env GETSENTRY_SAC_VERB=apply
  sudo-gcp
  tf-lock
  terragrunt run-all \
    apply --auto-approve
)

tf_log=tf-log.hcl
console_log=console.log
with-user-env "$TF_ROOT_MODULE" \
    "${cmd[@]}" 2>&1 >"$tf_log" |
  tee "$console_log" \
  && status=$? \
  || status=$? \
;

summary="$(
  if tac "$tf_log" | grep -E -im1 'complete'; then
    : :D
  elif cat "$console_log" "$tf_log" | grep -E -im1 'error'; then
    : D:
  else
    echo "summary failed!($?)"
  fi
)"

# TODO: hide "commands" in PR comments when exit code is 0
# TODO: hide tf-init and tf-refresh outputs from tf log -- run them separate?
gha-step-summary >/dev/null <<EOF
### TACOS Apply: $TF_ROOT_MODULE

Approvers: $GITHUB_PR_APPROVERS

<details>
  <summary>$summary</summary>

  Commands: (exit code: $status)

\`\`\`console
$(
  # match `console` syntax highlighting by removing '+ ' from xtrace lines
  uncolor "$console_log" |
    sed -r 's/^\++ \$ /\n$ /'
)
\`\`\`

  Result:

\`\`\`hcl
$(cat "$tf_log")
\`\`\`

</details>
EOF

exit "$status"
