#!/bin/bash
set -euo pipefail

# TODO: convert from matrix job to unlock slices "all at once"

cd "$GITHUB_WORKSPACE"
jq <<< "$TF_ROOT_MODULES" '.[]' -r |
  xargs -n1 "$TACOS_GHA_HOME/"lib/tacos/unlock |
  gha-step-summary \
;
