#!/bin/bash
set -euo pipefail
export TERRAGRUNT_INCLUDE_MODULE_PREFIX=false

# terragrunt in "bare" slices will evaluate relative paths with respect to its
# hidden terraform working directory, making the plan file hard to find, so
# it's essential to use an absolute path here.
export TACOS_TFPLAN="$PWD/$TF_ROOT_MODULE/tfplan"

# TODO: let the user know who has the lock
# TODO: let the user know plan may not be fully accurate, if they dont have the lock

if "$GITHUB_PR_DRAFT"; then
  export TACOS_LOCK=false
else
  export TACOS_LOCK=true
fi

gha-set-artifact result/tfplan <<< "$TF_ROOT_MODULE/tfplan"

exec tf-step-summary "TACOS Plan" "$TACOS_GHA_HOME/"lib/tacos/plan
