#!/bin/bash
set -euo pipefail
exec 1>&2  # stdout is reserved for tf plan/apply results
log=plan-log.hcl
sudo-gcp sh -c '
tf-lock-release | tee plan-log.hcl
'
summary="$(cat $log)"
gha-step-summary "$summary"
