#!/bin/bash
set -euo pipefail
set -ex
exec 1>&2  # stdout is reserved for tf plan/apply results
(
    echo "### TACOS Unlock"
    echo
    if results=$(xargs -r -P20 -n1 unlock-one 2>&1); then
    cat <<EOF
<details>
<summary>
Success! all slices have been unlocked.
</summary>
\`\`\`console
$results
\`\`\`
</details>
EOF
    else
    cat <<EOF 
<details>
<summary> 
Some slices failed to unlock.
</summary>
\`\`\`console
$results
\`\`\`
</details>
EOF
    fi
) | gha-step-summary;
