#!/bin/bash
set -euo pipefail
exec >&2  # only logs here

if [[ "$*" ]]; then
  suffix=" ($*)"
else
  suffix=""
fi

echo ::group::GitHub Actions Environment"$suffix"
"$TACOS_GHA_HOME/"lib/unix/env-sorted
echo ::endgroup::
