#!/bin/bash
# Forward stdin to the GHA step summary, and save it to the .summary output of
# this step.
set -euo pipefail

tee >(
  # step summary and PR comments can't handle ansi-color like GHA logging does =(
  uncolor |
    tee -a "$GITHUB_STEP_SUMMARY" |
    jq -sR |
    gha-set-output summary \
  >/dev/null
)
