#!/bin/bash
# Run the wrapped command to generate the GHA step summary.
# The summary is also saved to the .summary output of this step.
set -euxo pipefail

# these can't handle ansi-color like GHA logging does =(
uncolor |
tee -a "$GITHUB_STEP_SUMMARY" |
  gha-set-output summary jq -sR
