#!/bin/bash
set -euo pipefail
trap 'echo "FAIL($?)"' ERR


test_secrets='
  {
    "a": "b",
    "c d'\''\"; echo ef": "g h'\''\"; echo ij",
    "klm%&nop": "qrs%=&\n\rtuv"
  }
'

expected=$(cat <<'EOF'
::add-mask::b
  >>GITHUB_ENV a<<EOsecret
  >>GITHUB_ENV b
  >>GITHUB_ENV EOsecret
::add-mask::g h'"; echo ij
  >>GITHUB_ENV c d'"; echo ef<<EOsecret
  >>GITHUB_ENV g h'"; echo ij
  >>GITHUB_ENV EOsecret
::add-mask::qrs%25=&%0A%0Dtuv
  >>GITHUB_ENV klm%&nop<<EOsecret
  >>GITHUB_ENV qrs%=&
  >>GITHUB_ENV tuv
  >>GITHUB_ENV EOsecret
EOF
)

actual="$(
  env GITHUB_ENV=>(sed -ur 's/^/  >>GITHUB_ENV /') \
    gha-set-secrets <<< "$test_secrets" \
  ;
)"


diff -u <(echo "$expected") <(echo "$actual")
echo "PASS"
