#!/bin/bash
set -euo pipefail
echo "FIRST PARAM {$1}"
var="$1"
shift 1
trap 'echo "ERROR($?)"' ERR

gha_escape() {
  # see https://github.com/search?q=repo%3Aactions/toolkit%20escapeData&type=code
  sed -z 's/\n$//; s/%/%25/g; s/\r/%0D/g; s/\n/%0A/g'
}

# capture a copy of stdin
val="$(cat)"
# correctly handle multiline secrets:
mask_val="$(echo -n "$val" | sed -z 's/%/%25/g; s/\r/%0D/g; s/\n/%0A/g')"


echo "::add-mask::$mask_val"

cat <<EOF >> "$GITHUB_ENV"
$var<<EOsecret
$val
EOsecret
EOF
