#!/bin/bash
set -euo pipefail
var="$1"
trap 'echo "ERROR($?)"' ERR


# capture a copy of stdin, while streaming it to stdout, too
exec 3>&1  # copy stdout
val="$(tee >(cat >&3))"


# NOTE: separate subprocess substitution, above, to avoid separating var from
#   value due to reentrancy
result="$var=$val"
cat >> "$GITHUB_OUTPUT" <<< "$result"

if (( ${DEBUG:-0} > 1 )); then
  echo >&2 "gha-set-output: $result"
fi
