#!/bin/bash
set -euo pipefail

get_line() {
  config_file="$1"
  grep -Ev -m1 '^\s*(#|$)' "$config_file" && status=$? || status=$?
  if (( status == 1 )); then
    : grep found nothing
  else
    # error!
    return "$status"
  fi
}
interpolate_line() {
  config_file="$1"

  val="$(get_line "$config_file")"

  # support interpolating ${X:-${Y:-xyz}} for dynamic config and defaults
  # TODO: interpolate with a python (rust?) script, for less abitrary execution
  /bin/sh -ec 'echo "'"$val"'"'
}

if (( DEBUG >= 1 )); then
  set -x
fi

if config="$(nearest-config-file .config/sudo-gcp/service-account)"; then
  interpolate_line "$config"

# TODO: clean up `sudo-gcp.toml` configs, then delete me:
elif config="$(nearest-config-file sudo-gcp.d/service-account)"; then
  interpolate_line "$config"

# TODO: clean up `sudo-gcp.toml` configs, then delete me:
elif config="$(nearest-config-file sudo-gcp.toml)"; then
  toml get "$config" service_account --raw

# TODO: clean up `sac-terraformer` configs, then delete me:
elif config="$(nearest-config-file sac-terraformer)"; then
  interpolate_line "$config"

else
  cat >&2 <<EOF
Unable to find the correct service account for your terraform.
Please add a .config/sudo-gcp/service-account file to your project.

https://github.com/getsentry/sudo-gcp
EOF
  exit 1

fi
