#!/bin/bash
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"

export DEBUG="${DEBUG:-}"
if (( DEBUG >= 1 )); then
  set -x
fi

# FIXME: support `-u $USER` and/or `-u $EMAIL` to request an end-user access token
if [[ "${1:-}" = "-u" ]]; then
  shift 1
  service_account=("$1")
  shift 1
elif [[ "${1:-}" =~ ^- ]]; then
  echo >&2 'usage: sudo-gcp-export [-u $GCP_SERVICE_ACCOUNT] [SHELL]'
  exit 1
else
  service_account=(
    "${SUDO_GCP_SERVICE_ACCOUNT:-"$(
      "$HERE/"sudo-gcp-service-account
    )"}"
  )
fi

shell="${1:-${SHELL:-bash}}"

env SHELL="$shell" \
  "$HERE/"gcloud-auth-export-access-token "${service_account[@]}"
