name: scratch
description: test custom action

inputs:
  shell:
    #default: env ./lib/ci/default-shell {0}
    default: bash -euxo pipefail {0}

runs:
  using: composite
  steps:
    - name: ok
      shell: ${{inputs.shell}}
      run: echo ok

    - name: show env (before)
      shell: ${{inputs.shell}}
      run: |
        sort -z /proc/self/environ |
          tr '\0\n' '\n;' \
          > pre-action.env
        git diff --no-index --color-word='([[:alnum:]_]+|.)' -U0 orig.env pre-action.env || :

    - name: show full context
      shell: ${{inputs.shell}}
      run: |
        : <<'EOF'
        github:   ${{ toJSON(github) }},
        env:      ${{ toJSON(env) }},
        vars:     # not valid in custom action
        job:      ${{ toJSON(job) }},
        jobs:     # for reusable workflows only
        steps:    ${{ toJSON(steps) }},
        runner:   ${{ toJSON(runner) }},
        secrets:  # not valid in custom action
        strategy: ${{ toJSON(strategy) }},
        matrix:   ${{ toJSON(matrix) }},
        needs:    # not valid in custom action
        inputs:   ${{ toJSON(inputs) }},
        EOF

    - name: show unix infos (before)
      shell: ${{inputs.shell}}
      run: |
        whoami
        id
        hostname
        hostname -f
        uname --nodename
        uname --kernel-release
        uname --kernel-version
        uname --machine
        uname --processor
        uname --hardware-platform
        uname --operating-system

    - name: Set username and hostname
      uses: ./.github/actions/set-username-and-hostname
      with:
        user: ${{github.triggering_actor}}

    - name: show unix infos (after)
      shell: ${{inputs.shell}}
      run: |
        whoami
        id
        hostname
        hostname -f
        uname --nodename
        uname --kernel-release
        uname --kernel-version
        uname --machine
        uname --processor
        uname --hardware-platform
        uname --operating-system

    - name: show env (after)
      shell: ${{inputs.shell}}
      run: |
        sort -z /proc/self/environ |
          tr '\0\n' '\n;' \
          > post-action.env
        git diff --no-index --color-word='([[:alnum:]_]+|.)' -U0 orig.env post-action.env || :
