#!/bin/bash
set -euxo pipefail

response="${1:-./01-device-code.result.json}"

user_code="$(jq -r .user_code < "$response")"
verification_uri="$(jq -r .verification_uri < "$response")"

set -x

: Please enter your code: "$user_code"
open "$verification_uri"
