#!/bin/bash
set -eEuo pipefail
HERE="$(dirname "$(readlink -f "$0")")"

. "$HERE/"lib/env.sh

if [[ "${DEBUG:-}" ]]; then
  set -x
fi

if [[ $# -lt 2 ]]; then
  ESC=$'\033'
  cat >&2 <<EOF
usage: tf-lock [TF_MODULE=\$PWD] COMMAND ...

Run COMMAND while holding the state lock of TF_MODULE.

This command will succeed if the terraform state lock is currently unheld or if
it is currently held by ${ESC}[34m$(whoami)@$(hostname -f)${ESC}[m (i.e. ${ESC}[32m\$(whoami)@\$(hostname -f)${ESC}[m).
It will fail if anyone else holds the lock.

COMMAND should take the state lock, itself (e.g. \`terraform apply\`). The state
lock will continue to be held after the command finishes.
EOF
  exit 1
elif [[ -d "$1" ]]; then
  slice="$1"
  shift 1
else
  slice="."
fi

"$HERE/"tf-lock-release "$slice"
"$@"
"$HERE/"tf-lock-acquire "$slice"
