#!/bin/bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")"; pwd)"
root_module="${1:-"$PWD"}"

if [[ "${DEBUG:-}" ]]; then
  set -x
fi

lock_id=$(
  "$HERE/"tf-lock-id "$root_module"
) && status=$? || status=$?

if (( status == 2 )); then
  ( cd "$root_module"
    if ! "$HERE/"lib/tf_lock_acquire.py; then
      echo >&2 lock not obtained!
      exit 1
    fi
  )
  exec "$HERE/"tf-lock-id "$root_module"
elif (( status == 0 )); then
  # already done!
  cat <<< "$lock_id"
  exit 0
else
  # surface any unexpected errors
  cat >&2 <<< "$lock_id"
  exit "$status"
fi
