#!/bin/bash
set -euo pipefail

get_line() {
  config_file="$1"
  grep -Ev -m1 '^\s*(#|$)' "$config_file"
}

if config="$(nearest-config-file sudo-gcp.d)"; then
  # note: we're using `eval` to interpolate $variables
  # TODO: interpolate without executing arbitrary shell code
  eval 'echo "'"$(get_line "$config/service-account")"'"'

# TODO: clean up `sudo-gcp.toml` configs, then delete me:
elif config="$(nearest-config-file sudo-gcp.toml)"; then
  toml get "$config" service_account --raw

# TODO: clean up `sac-terraformer` configs, then delete me:
elif config="$(nearest-config-file sac-terraformer)"; then
  get_line "$config"

else
  cat >&2 <<EOF
Unable to find the correct service account for your terraform.
Please add a sudo-gcp.toml file to your project.

https://github.com/getsentry/sudo-gcp
EOF
  exit 1

fi
