#!/bin/bash
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"
PATH="$HERE:$HERE/../gcloud:$HERE/../unix:$PATH"
sac_terraformer="${GETSENTRY_SAC_TERRAFORMER:-"$(sac-terraformer)"}"
sudo-gcp -u "$sac_terraformer" "$@"
