#!/bin/bash
set -euxo pipefail

sshdir="$HOME"/.ssh
echo "$sshdir"
mkdir "$sshdir"
chmod 700 "$sshdir"
cat > "$sshdir"/key
chmod 600 "$sshdir"/key
eval "$(ssh-agent -s)"
gha-set-env SSH_AUTH_SOCK <<< "$SSH_AUTH_SOCK"
gha-set-env SSH_AGENT_PID <<< "$SSH_AGENT_PID"
ssh-add "$sshdir"/key
