#!/bin/bash
set -euo pipefail
# read as: cp stdout tmp && cp stderr stdout
# stdout is reserved for tf plan results
exec 3>&1 1>&2

( set -ex
  sudo-gcp tf-lock-acquire
)

if [ "${TERRAGRUNT_VERSION}" = "0.54.15" ]; then
    run_all=("run-all")
else
    run_all=("run" "--all" "--")
fi

quietly sudo-gcp terragrunt "${run_all[@]}" init
quietly sudo-gcp terragrunt "${run_all[@]}" refresh

set -x
: TODO: fetch and apply the tfplan artifact from plan workflow
sudo-gcp terragrunt "${run_all[@]}" apply --auto-approve >&3
