#!/bin/bash
set -euo pipefail
# read as: cp stdout tmp && cp stderr stdout
# stdout is reserved for tf plan results
exec 3>&1 1>&2

( set -ex
  sudo-gcp tf-lock-acquire
)

quietly sudo-gcp terragrunt run-all init
quietly sudo-gcp terragrunt run-all refresh

set -x
: TODO: fetch and apply the tfplan artifact from plan workflow
sudo-gcp terragrunt run-all apply --auto-approve >&3
