#!/bin/bash
set -euo pipefail
SHA1="${1:-HEAD^}"
SHA2="${2:-HEAD}"

set -x

#-s tottime
python -m cProfile -s tottime \
  -m lib.tacos.dependent_slices <(
  git diff  "$SHA1" "$SHA2" \
      --name-only \
      --diff-filter=ACMRT \
)
