#!/bin/bash
set -euo pipefail
SHA1="${1:-HEAD^}"
SHA2="${2:-HEAD}"
export PYTHONPATH="$TACOS_GHA_HOME"

set -x

python3.12 -Pm lib.tacos.dependent_slices <(
    git diff  "$SHA1" "$SHA2" \
        --name-only \
        --diff-filter=ACMRT \
  ) |
  # transform newline-delimited list into json:
  jq -R | jq -s \
;
