#!/bin/bash
set -euo pipefail

cache=.config/tf-lock-info

#todo: make this an artifact instead
# we expect at most 6 slices to be fighting
git_push_aggressively() {
  sleep=3
  limit=20 # 3 min 
  while ! (set -ex; git push -q); do
    if (( sleep > limit )); then exit 1; fi
    echo "failed! trying again after $sleep seconds..."
    sleep $sleep
    (( sleep += 3 ))
    (set -ex
    git pull --rebase origin "$GITHUB_HEAD_REF" 
    )
  done
}

if [[ -d $cache ]]; then
    git add -f $cache
    if ! git diff --cached --exit-code $cache; then
      git config --global user.email "$USER@$HOSTNAME"
      git config --global user.name "$USER"
      git config --global push.default current
      #git checkout -b "$GITHUB_HEAD_REF"
      ( set -ex
      git fetch origin --depth=1 "$GITHUB_HEAD_REF"
      git checkout "$GITHUB_HEAD_REF"
      # graft="$(git rev-parse HEAD)"
        # add .terraform-lock changes 
        git add -u .
        git status
        git commit -m "updating tf-lock cache: $TF_ROOT_MODULE"
      )
      git_push_aggressively
    fi
  fi