#!/bin/bash
set -euo pipefail
# read as: cp stdout tmp && cp stderr stdout
# stdout is reserved for tf plan results
exec 3>&1 1>&2

# note: for terragrunt, tfplan must be absolute
TACOS_TFPLAN="${TACOS_TFPLAN:-$PWD/tfplan}"
TACOS_LOCK="${TACOS_LOCK:-false}"
cache=.config/tf-lock-info

#todo: make this an artifact instead
# we expect at most 6 slices to be fighting
git_push_aggressively() {
  sleep=3
  limit=6
  # limit=20 # 3 min 
  # todo: git push -q 
  # git fetch --unshallow origin HEAD
  sleep $sleep # trying to force race condition
  while ! (set -ex; git push); do
    if (( sleep > limit )); then exit 1; fi
    echo "failed! trying again after $sleep seconds..."
    sleep $sleep
    (( sleep += 3 ))
    (set -ex
    #git fetch origin "$GITHUB_REF":refs/heads/pull.$sleep
    #git fetch --depth=2 origin "$GITHUB_REF":refs/heads/pull.$sleep
    git pull --rebase # --shallow-exclude="$graft" origin "$GITHUB_HEAD_REF"
    git log --oneline --graph --decorate --all
    )
    # git status
    # git log --oneline --graph --decorate --all
    # git fetch --depth=2 origin "$GITHUB_REF":refs/heads/pull.$sleep
    # git log --oneline --graph --decorate --all 
    # git rebase pull.$sleep
    # git log --oneline --graph --decorate --all)
    # (set -ex; git pull --rebase origin "$GITHUB_HEAD_REF")
  done
}

if "$TACOS_LOCK"; then
  ( set -ex
    env GETSENTRY_SAC_VERB=state-admin sudo-gcp tf-lock-acquire
  )
  if [[ -d $cache ]]; then
    git add -f $cache
    (set -ex 
    pwd 
    echo tf root module: "$TF_ROOT_MODULE"
    )
    if ! git diff --cached --exit-code $cache; then
      git config --global user.email "$USER@$HOSTNAME"
      git config --global user.name "$USER"
      git config --global push.default current
      #git checkout -b "$GITHUB_HEAD_REF"
      ( set -ex
      git fetch origin --depth=1 "$GITHUB_HEAD_REF"
      git checkout "$GITHUB_HEAD_REF"
      # graft="$(git rev-parse HEAD)"
        # add .terraform-lock changes 
        git add -u .
        git status
        git commit -m "updating tf-lock cache: $TF_ROOT_MODULE"
        git log --stat --oneline --graph --decorate --color=always 
      )
      git_push_aggressively
    fi
  fi
fi

quietly sudo-gcp terragrunt run-all init

if "$TACOS_LOCK"; then
  quietly sudo-gcp terragrunt run-all refresh
fi

set -x
sudo-gcp terragrunt run-all plan -out "$TACOS_TFPLAN" >&3
