#!/bin/bash
set -euo pipefail
# read as: cp stdout tmp && cp stderr stdout
# stdout is reserved for tf apply results
exec 3>&1 1>&2

# note: for terragrunt, tfplan must be absolute
TACOS_TFPLAN="${TACOS_TFPLAN:-$PWD/tfplan}"
TACOS_LOCK="${TACOS_LOCK:-false}"

if "$TACOS_LOCK"; then
  ( set -ex
    GETSENTRY_SAC_VERB=state-admin sudo-gcp tf-lock-acquire
  )
fi

quietly sudo-gcp terragrunt run-all init

if "$TACOS_LOCK"; then
  quietly sudo-gcp terragrunt run-all refresh
fi

set -x
sudo-gcp terragrunt run-all plan -out "$TACOS_TFPLAN" >&3
