#!/bin/bash
set -euo pipefail
HERE="$(dirname "$(readlink -f "$0")")"
TACOS_GHA_HOME="$(cd "$HERE"/../..; pwd)"
export PYTHONPATH="$TACOS_GHA_HOME${PYTHONPATH+:$PYTHONPATH}"


python3.12 -m lib.tacos.slices "$@" |
  python3.12 -m lib.tacos.path_filter \
;
