name: Required check

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable
    secrets:
      ssh-private-key:
        description: "Private SSH key to use for git clone"
        required: false

jobs:
  required_check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Perform check
        run: |
          if [ -e ../../required-check.fail ]; then exit 1; fi
