name: Reset Label

on:
  workflow_call:
    inputs:
      label:
        type: string
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable

jobs:
  reset_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    if: |
      true
      && github.event.action == 'labeled'
      && github.event.label.name == inputs.label

    env:
      LABEL: ${{ inputs.label }}

    steps:
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha
      - name: "Reset label: ${{inputs.label}}"
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const reset_label = require('./tacos-gha/.github/workflows/reset-label.js')
            reset_label({github, context, label: process.env.LABEL})
