name: Selftest Matrix IO

on:
  push:
    paths:
      - ".github/actions/matrix-fan-out/**"
      - ".github/actions/matrix-fan-in/**"
      - ".github/workflows/selftest-matrix-io.yml"

defaults:
  run:
    shell: bash -euxo pipefail {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  keys-job:
    runs-on: ubuntu-latest
    outputs:
      keys: ${{ steps.keys-step.outputs.keys }}
    steps:
      - name: Generate matrix-jobs' keys
        id: keys-step
        run: |
          exec >&2  # our only output is logging
          printf "keys=[10, 27]" >> "$GITHUB_OUTPUT"
          # for scale testing:
          ###seq 30 | shuf | jq -R | jq -cs | tee -a "$GITHUB_OUTPUT"

  fan-out:
    runs-on: ubuntu-latest
    needs:
      - keys-job
    strategy:
      matrix:
        key: ${{ fromJSON(needs.keys-job.outputs.keys) }}
    env:
      KEY: ${{ matrix.key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: tacos-gha
          sparse-checkout: ".github/actions/matrix-fan-out"
          sparse-checkout-cone-mode: false

      - name: Add content to fan-out
        id: content
        run: |
          "./tacos-gha/".github/actions/matrix-fan-out/selftest.sh "$KEY"

      - name: Run matrix-fan-out
        uses: ./tacos-gha/.github/actions/matrix-fan-out
        with:
          path: ./a/b/c
          steps: "${{ toJSON(steps) }}"
          retention-days: 1

  fan-in:
    runs-on: ubuntu-latest
    needs: fan-out
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: tacos-gha
          sparse-checkout: |
            .github/actions/matrix-fan-out
            .github/actions/matrix-fan-in
          sparse-checkout-cone-mode: false

      - name: Run matrix-fan-in
        uses: ./tacos-gha/.github/actions/matrix-fan-in
        with:
          path: a/b/c

      - name: Check matrix-fan-in.json
        run: |
          "./tacos-gha/".github/actions/matrix-fan-in/selftest.sh
