name: Selftest Matrix IO

on:
  push:
    paths:
      - '.github/actions/matrix-fanout/**'
      - '.github/actions/matrix-fanin/**'
      - '.github/workflows/selftest-matrix-io.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-file: ['test1', 'test2']
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add content to json file
        shell: bash
        run: |
          echo '{"${{ matrix.json-file }}": "test"}' > ${{ matrix.json-file }}.json
    
      - name: Run matrix-fanout
        uses: ./.github/actions/matrix-fanout
        with:
          json-file: ${{ matrix.json-file }}

  fanin:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run matrix-fanin
        uses: ./.github/actions/matrix-fanin
      
      - name: Check matrix-fanin.json
        shell: bash
        run: |
          cat matrix-fanin.json
          jq -e '.test1 == "test"' matrix-fanin.json
          jq -e '.test2 == "test"' matrix-fanin.json

