name: Selftest Matrix IO

on:
  push:
    paths:
      - '.github/actions/matrix-fanout/**'
      - '.github/actions/matrix-fanin/**'
      - '.github/workflows/selftest-matrix-io.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add content to json file
        shell: bash
        run: |
          echo '{"MATRIX_KEY${{ matrix.key }}": ${{ matrix.key }}}' > test${{ matrix.key }}.json
    
      - name: Run matrix-fanout
        uses: ./.github/actions/matrix-fanout
        with:
          json-file: test${{ matrix.key }}

  fanin:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run matrix-fanin
        uses: ./.github/actions/matrix-fanin
      
      - name: Check matrix-fanin.json
        shell: bash
        run: |
          cat matrix-fanin.json

