name: TACOS Plan

# downstream projects should use events:
###pull_request:
###  types: [labeled, opened, synchronize, reopened, ready_for_review]

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable
      debug:
        type: string
        default: 0
    secrets:
      ssh-private-key:
        description: "Private SSH key to use for git clone"
        required: false
      tf-provider-secrets:
        description: |
          Json map containing the secrets TF providers need to operate.
          Each entry of the map represents a secret. 
          Each secret (example: `PAGERDUTY_TOKEN: zxczxcz...`) is unpacked
          and set as TF_VAR environment variable: `TF_VAR_PAGERDUTY_TOKEN`
          in this case.
        required: false
      

defaults:
  run:
    shell: env ./tacos-gha/lib/ci/default-shell {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# FIXME: only use state-admin access for a locking (non-draft) plan
env:
  GETSENTRY_SAC_VERB: state-admin
  DEBUG: ${{inputs.debug}}

jobs:
  determine-tf-root-modules:
    name: List Slices
    if: |
      false
      || github.event.action != 'labeled'
      || github.event.label.name == ':taco::plan'
    outputs:
      slices: ${{ steps.list-slices.outputs.slices }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: List Slices
        id: list-slices
        uses: ./tacos-gha/.github/actions/list-slices

  tacos_plan:
    name: TACOS Plan
    needs: [determine-tf-root-modules]
    if: |
      needs.determine-tf-root-modules.outputs.slices != '[]'
    strategy:
      fail-fast: false
      matrix:
        tf-root-module:
          ${{ fromJSON(needs.determine-tf-root-modules.outputs.slices) }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    env:
      TF_ROOT_MODULE: ${{matrix.tf-root-module}}
    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha
      - name: Setup
        uses: ./tacos-gha/.github/actions/setup
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}
          tf-provider-secrets: ${{ inputs.tf-provider-secrets }}
          # We explicitly list the low-concern actions, during which users will
          # recieve a higher level of access -- the identity of the original PR
          # author. All other actions will receive lower access -- the identity
          # of the person pushing the "Re-run" button.
          #
          # see doc/permissions.md
          user: |-
            ${{
              true
              && github.event_name == 'pull_request'
              && (
                  false
                  || (
                      true
                      && github.event.action == 'labeled'
                      && github.event.label.name == ':taco::plan'
                  )
                  || github.event.action == 'ready_for_review'
                  || github.event.action == 'synchronize'
                  || github.event.action == 'reopened'
              )

              && github.event.pull_request.user.login

              || github.triggering_actor
            }}

      - name: Plan
        id: main
        run: |
          "$TACOS_GHA_HOME/"lib/ci/tacos-plan

      - name: Save matrix result
        # we need to show any errors to end-users
        if: always()
        uses: ./tacos-gha/.github/actions/matrix-fan-out

  summary:
    needs: tacos_plan
    # we need to report failures, too
    if: always() && needs.tacos_plan.result != 'skipped'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: Setup
        uses: ./tacos-gha/.github/actions/just-the-basics
      - name: Run matrix-fan-in
        uses: ./tacos-gha/.github/actions/matrix-fan-in
      - name: Summarize
        id: summary
        run: |
          ./tacos-gha/lib/ci/tacos-plan-summary |
            gha-step-summary

      - name: Update PR
        # we want to report failures, too
        if: always()

        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          message: ${{ fromJSON(steps.summary.outputs.summary) }}
          comment_tag: plan
          mode: recreate

  reset-label:
    uses: ./.github/workflows/reset-label.yml
    with:
      label: ":taco::plan"
      tacos_gha_repo: ${{inputs.tacos_gha_repo}}
      tacos_gha_ref: ${{inputs.tacos_gha_ref}}
