name: TACOS Plan

# downstream projects should use events:
###pull_request:
###  types: [opened, synchronize, reopened, ready_for_review]

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable
    secrets:
      ssh-private-key:
        description: "Private SSH key to use for git clone"
        required: false

defaults:
  run:
    shell: env ./tacos-gha/lib/ci/default-shell {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# FIXME: don't use the apply terraformer for the plan workflow
# problem: currently the plan terraformer is very strictly readonly but we need
#     to be able to lock/unlock the tfstate in this workflow
# proposals:
#   1. add a third "planlock" member to the terraformer? We want to grant write
#       permissions just enough for locking state.
#   2. add an ACL to grant this specific permission, but this is deprecated
#       https://cloud.google.com/storage/docs/access-control/lists
#   3. use conditional IAM (i.e. add some CEL code) to condtionally grant the
#       planner write to just the lock file
env:
  GETSENTRY_SAC_VERB: apply

jobs:
  determine-tf-root-modules:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    name: list slices
    outputs:
      slices: ${{ steps.main.outputs.slices }}

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: Determine Slices
        id: main
        uses: ./tacos-gha/.github/actions/determine-slices

  tacos_plan:
    if: |
      false
      || github.event.action != 'labeled'
      || github.event.label.name == ':taco::plan'
    needs: [determine-tf-root-modules]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        tf-root-module:
          ${{ fromJSON(needs.determine-tf-root-modules.outputs.slices) }}

    env:
      TF_ROOT_MODULE: ${{matrix.tf-root-module}}

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha
      - name: Setup
        uses: ./tacos-gha/.github/actions/setup
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}

      - name: Plan
        id: main
        run: |
          "$TACOS_GHA_HOME/"lib/ci/tacos-plan

      - name: Update PR
        # we want to report failures, too
        if: always()
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          message: ${{ fromJSON(steps.main.outputs.summary) }}
          comment_tag: plan(${{env.TF_ROOT_MODULE}})

      - name: Store `tfplan`
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.main.outputs.artifact_name}}
          path: ${{steps.main.outputs.artifact_path}}
          if-no-files-found: error
          overwrite: true # we only want the latest plan

  # FIXME: we need a fan-in summary
  # summary:

  reset-label:
    uses: ./.github/workflows/reset-label.yml
    with:
      label: ":taco::plan"
      tacos_gha_repo: ${{inputs.tacos_gha_repo}}
      tacos_gha_ref: ${{inputs.tacos_gha_ref}}
