name: TACOS Apply

# downstream projects should use events:
###pull_request:
###  types: [labeled]

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable
    secrets:
      ssh-private-key:
        description: "Private SSH key to use for git clone"
        required: false

defaults:
  run:
    shell: env ./tacos-gha/lib/ci/default-shell {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GETSENTRY_SAC_VERB: apply

jobs:
  determine-tf-root-modules:
    name: List Slices
    # note: we want to noop if they converted to draft first
    if: |
      true
      && github.event.action == 'labeled'
      && github.event.label.name == ':taco::apply'
      && github.event.pull_request.draft == false
    outputs:
      slices: ${{ steps.list-slices.outputs.slices }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: List Slices
        id: list-slices
        uses: ./tacos-gha/.github/actions/list-slices

  tacos_apply:
    name: TACOS Apply
    needs: [determine-tf-root-modules]
    if: |
      needs.determine-tf-root-modules.outputs.slices != '[]'
    strategy:
      fail-fast: false
      matrix:
        tf-root-module:
          ${{ fromJSON(needs.determine-tf-root-modules.outputs.slices) }}

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    env:
      TF_ROOT_MODULE: ${{matrix.tf-root-module}}
    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha
      - name: Setup
        uses: ./tacos-gha/.github/actions/setup
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}

      # TODO: fetch and apply the tfplan artifact from plan workflow
      # so that apply matches the plan reviewed by construction
      ### - name: fetch tfplan: ${{which}}
      ###   uses: actions/download-artifact@v4
      ###   with:
      ###     name: tfplan
      ###     # TODO: github-script to fetch run-id of the most recent tfplan
      ###     run-id: ${{steps.find-plan.output.run-id}}

      - name: set $GITHUB_PR_*
        run: |
          "$TACOS_GHA_HOME/"lib/ci/github-pr-setenv "${{ github.event.pull_request.html_url }}"

      - name: Apply
        id: main
        run: |
          "$TACOS_GHA_HOME/"lib/ci/tacos-apply

      - name: Save matrix result
        # we need to show any errors to end-users
        if: always()
        uses: ./tacos-gha/.github/actions/matrix-fan-out

  summary:
    needs: tacos_apply
    # we need to report failures, too
    if: always() && needs.tacos_apply.result != 'skipped'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: Setup
        uses: ./tacos-gha/.github/actions/just-the-basics
      - name: Run matrix-fan-in
        uses: ./tacos-gha/.github/actions/matrix-fan-in
      - name: Summarize
        id: summary
        run: |
          ./tacos-gha/lib/ci/tacos-apply-summary |
            gha-step-summary

      - name: Update PR
        # we want to report failures, too
        if: always()

        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          message: ${{ fromJSON(steps.summary.outputs.summary) }}
          comment_tag: apply
          mode: recreate

  reset-label:
    uses: ./.github/workflows/reset-label.yml
    with:
      label: ":taco::apply"
      tacos_gha_repo: ${{inputs.tacos_gha_repo}}
      tacos_gha_ref: ${{inputs.tacos_gha_ref}}
