name: TACOS Detect Drift

# downstream projects should use events:
###schedule:
###  - cron: "0 0 * * *"

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable
    secrets:
      ssh-private-key:
        description: "Private SSH key to use for git clone"
        required: false
      tf-provider-secrets:
        description: |
          Json map containing the secrets TF providers need to operate.
          Each entry of the map represents a secret. 
          Each secret (example: `PAGERDUTY_TOKEN: zxczxcz...`) is unpacked
          and set as TF_VAR environment variable: `TF_VAR_PAGERDUTY_TOKEN`
          in this case.
        required: false

defaults:
  run:
    shell: env ./tacos-gha/lib/ci/default-shell {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  determine-tf-root-modules:
    name: List Slices
    if: github.event.pull_request.draft == false
    outputs:
      slices: ${{ steps.list-slices.outputs.slices }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: List All Slices
        id: list-slices
        run: |
          # NB: separate subprocess substitution, to avoid masking return values
          slices="$("./tacos-gha/"lib/tacos/slices | jq -R | jq -sc)"
          tee -a "$GITHUB_OUTPUT" <<< "slices=$slices"

  # TODO: should we detect drift in parallel across every slice?
  tacos_detect_drift:
    name: TACOS Drift Detection
    needs: [determine-tf-root-modules]
    if: |
      needs.determine-tf-root-modules.outputs.slices != '[]'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    env:
      TF_ROOT_MODULES: ${{needs.determine-tf-root-modules.outputs.slices}}
    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha
      - name: Setup
        uses: ./tacos-gha/.github/actions/setup
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}
          tf-provider-secrets: ${{ secrets.tf-provider-secrets }}

      - name: Detect drift
        run: |
          gha-log-as-step-summary "$TACOS_GHA_HOME/"lib/ci/tacos-detect-drift
