name: TACOS Apply

# downstream projects should use events:
###pull_request:
###  types: [labeled]

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable

defaults:
  run:
    shell: env ./tacos-gha/lib/ci/default-shell {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GETSENTRY_SAC_VERB: apply

jobs:
  tacos_apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    # note: we want to noop if they converted to draft first
    if: |
      true
      && github.event.label.name == ':taco::apply'
      && github.event.pull_request.draft == false

    steps:
      - uses: bukzor/direnv-install@v1
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: show event
        run: |
          : <<'EOF'
            ${{toJSON(github.event)}}
          EOF

      - name: tell TF username and PR
        uses: ./tacos-gha/.github/actions/set-username-and-hostname

      - name: set workload identity provider
        id: set-workload-identity-provider
        run: ./tacos-gha/lib/ci/set-workload-identity-provider

      - name: set terraformer
        id: set-terraformer
        working-directory: ${{ env.working_dir }}
        run: ./tacos-gha/lib/ci/set-terraformer

      - name: gcp auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{env.GETSENTRY_SAC_OIDC}}
          service_account: ${{env.GETSENTRY_SAC_TERRAFORMER}}

      - name: Obtain the lock
        run: |
          ./tacos-gha/lib/github/log-as-step-summary ./tacos-gha/lib/ci/obtain-lock

      # this should really be default behavior:
      - run: |
          gha-set-env 'TF_VERSION' cat .terraform-version
          gha-set-env 'TERRAGRUNT_VERSION' cat .terragrunt-version

      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "run-all apply --auto-approve"
          tg_comment: 1

  reset_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    if: |
      github.event.label.name == ':taco::apply'

    steps:
      - name: Reset label
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ':taco::apply'
            })
