name: TACOS Plan

# downstream projects should use events:
###pull_request:
###  types: [labeled, opened, synchronize, reopened, ready_for_review]

on:
  workflow_call:
    inputs:
      tacos_gha_repo:
        type: string
        default: getsentry/tacos-gha
      tacos_gha_ref:
        type: string
        default: refs/heads/stable
    secrets:
      ssh-private-key:
        description: "Private SSH key to use for git clone"
        required: false

defaults:
  run:
    shell: env ./tacos-gha/lib/ci/default-shell {0}

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# FIXME: only use state-admin access for a locking (non-draft) plan
env:
  GETSENTRY_SAC_VERB: state-admin

jobs:
  determine-tf-root-modules:
    if: |
      false
      || github.event.action != 'labeled'
      || github.event.label.name == ':taco::plan'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    name: list slices
    outputs:
      slices: ${{ steps.list-slices.outputs.slices }}

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha

      - name: List Slices
        id: list-slices
        uses: ./tacos-gha/.github/actions/list-slices
        with:
          allowlist: .config/tacos-gha/plan.allowlist

  tacos_plan:
    needs: [determine-tf-root-modules]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        tf-root-module:
          ${{ fromJSON(needs.determine-tf-root-modules.outputs.slices) }}

    env:
      TF_ROOT_MODULE: ${{matrix.tf-root-module}}

    steps:
      - name: Checkout IAC
        uses: actions/checkout@v4
      - name: Checkout tacos-gha
        uses: actions/checkout@v4
        with:
          repository: ${{inputs.tacos_gha_repo}}
          ref: ${{inputs.tacos_gha_ref}}
          path: tacos-gha
      - name: Setup
        uses: ./tacos-gha/.github/actions/setup
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}
          # We explicitly list the low-concern actions, during which users
          # will use the identity of the original PR author.
          # see doc/permissions.md
          user: |
            ${{
              true
              && github.event_name == 'pull_request'
              && (
                  false
                  || (
                      true
                      && github.event.action == 'labeled'
                      && github.event.label.name == ':taco::plan'
                  )
                  || github.event.action == 'ready_for_review'
                  || github.event.action == 'synchronize'
                  || github.event.action == 'reopened'
              )

              && github.event.pull_request.user.login

              || github.triggering_actor
            }}

      - name: Plan
        id: main
        run: |
          "$TACOS_GHA_HOME/"lib/ci/tacos-plan

      - name: Update PR
        # we want to report failures, too
        if: always()
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          message: ${{ fromJSON(steps.main.outputs.summary) }}
          comment_tag: plan(${{env.TF_ROOT_MODULE}})

      - name: Store `tfplan`
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.main.outputs.artifact_name}}
          path: ${{steps.main.outputs.artifact_path}}
          if-no-files-found: error
          overwrite: true # we only want the latest plan

  # FIXME: we need a fan-in summary
  # summary:

  reset-label:
    uses: ./.github/workflows/reset-label.yml
    with:
      label: ":taco::plan"
      tacos_gha_repo: ${{inputs.tacos_gha_repo}}
      tacos_gha_ref: ${{inputs.tacos_gha_ref}}
