name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: env ./lib/ci/default-shell {0}

env:
  # NOTE: please keep these in sync with ../../.terra*-version
  tf_version: "1.6.4"
  tg_version: "0.53.5"
  working_dir: "."
  deploy_environ: "dev"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: HatsuneMiku3939/direnv-action@v1

      - name: show event
        run: |
          : <<'EOF'
            ${{toJSON(github.event)}}
          EOF

      - name: set workload identity provider
        id: set-workload-identity-provider
        run: ./lib/ci/set-workload-identity-provider "$deploy_environ"

      - name: set terraformer
        id: set-terraformer
        working-directory: ${{ env.working_dir }}
        run: ./lib/ci/set-terraformer

      - name: gcp auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{steps.set-workload-identity-provider.outputs.workload_identity_provider}}
          service_account: ${{steps.set-terraformer.outputs.terraformer}}

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "run-all plan"
          tg_comment: 1
